import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/desktopthirtytwo">DesktopThirtyTwo</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/signup">Signup</Link>
        </li>
        <li>
          <Link to="/desktoptwo">DesktopTwo</Link>
        </li>
        <li>
          <Link to="/desktopfifteen">DesktopFifteen</Link>
        </li>
        <li>
          <Link to="/forgotpasswordone">ForgotPasswordOne</Link>
        </li>
        <li>
          <Link to="/forgotpassword">ForgotPassword</Link>
        </li>
        <li>
          <Link to="/changepassword">ChangePassword</Link>
        </li>
        <li>
          <Link to="/desktopthirtythree">DesktopThirtyThree</Link>
        </li>
        <li>
          <Link to="/meesages">Meesages</Link>
        </li>
        <li>
          <Link to="/desktopthirty">DesktopThirty</Link>
        </li>
        <li>
          <Link to="/desktopthirtyone">DesktopThirtyOne</Link>
        </li>
        <li>
          <Link to="/desktoptwentynine">DesktopTwentyNine</Link>
        </li>
        <li>
          <Link to="/a">A</Link>
        </li>
        <li>
          <Link to="/becomeamemberone">BecomeamemberOne</Link>
        </li>
        <li>
          <Link to="/profileedit">ProfileEdit</Link>
        </li>
        <li>
          <Link to="/desktopthirtysix">DesktopThirtySix</Link>
        </li>
        <li>
          <Link to="/desktoptwentythree">DesktopTwentyThree</Link>
        </li>
        <li>
          <Link to="/desktopthirtyseven">DesktopThirtySeven</Link>
        </li>
        <li>
          <Link to="/divdtindexfoot">Divdtindexfoot</Link>
        </li>
        <li>
          <Link to="/becomeamember">Becomeamember</Link>
        </li>
        <li>
          <Link to="/desktoptwentyfive">DesktopTwentyFive</Link>
        </li>
        <li>
          <Link to="/desktoptwentysix">DesktopTwentySix</Link>
        </li>
        <li>
          <Link to="/desktopthirtyfour">DesktopThirtyFour</Link>
        </li>
        <li>
          <Link to="/desktopthirtyfive">DesktopThirtyFive</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
