import React from "react";

const sizeClasses = {
  txtArialNarrowItalic12Red30002: "font-arial font-normal",
  txtSpartanRegular22: "font-normal font-spartan",
  txtRobotoBold14Red700: "font-bold font-roboto",
  txtArialBoldMT12: "font-arial font-bold",
  txtRobotoRegular15IndigoA400: "font-normal font-roboto",
  txtOpenSansRegular14Blue80001: "font-normal font-opensans",
  txtInterRegular12WhiteA700: "font-inter font-normal italic",
  txtRobotoRegular14Black90099: "font-normal font-roboto",
  txtAsapRegular16AmberA20001: "font-asap font-normal",
  txtSegoeUI30: "font-normal font-segoeui",
  txtRobotoRegular15WhiteA700: "font-normal font-roboto",
  txtSegoeUI36: "font-normal font-segoeui",
  txtFuzzyBubblesRegular14: "font-fuzzybubbles font-normal",
  txtFuzzyBubblesRegular16: "font-fuzzybubbles font-normal",
  txtInterSemiBold30: "font-inter font-semibold",
  txtInterRegular22: "font-inter font-normal",
  txtOpenSansBold14WhiteA700: "font-bold font-opensans",
  txtInterRegular8: "font-inter font-normal",
  txtAsapRegular21: "font-asap font-normal",
  txtRobotoBold14Gray60001: "font-bold font-roboto",
  txtPoppinsBlack16: "font-black font-poppins",
  txtAsapRegular16: "font-asap font-normal",
  txtMontserratRegular15Gray800: "font-montserrat font-normal",
  txtOpenSansBold36: "font-bold font-opensans",
  txtOpenSansRegular14: "font-normal font-opensans",
  txtOpenSansBold32: "font-bold font-opensans",
  txtOpenSansRegular12: "font-normal font-opensans",
  txtOpenSansRegular11: "font-normal font-opensans",
  txtRobotoRegular14RedA70001: "font-normal font-roboto",
  txtFuzzyBubblesRegular16Black900: "font-fuzzybubbles font-normal",
  txtSegoeUIBold60: "font-bold font-segoeui",
  txtAsapRegular14: "font-asap font-normal",
  txtInterRegular12: "font-inter font-normal",
  txtArialBoldMT12LightblueA100: "font-arial font-bold",
  txtArialBoldMT11: "font-arial font-bold",
  txtAsapRegular10: "font-asap font-normal",
  txtMontserratRegular24Black900dd: "font-montserrat font-normal",
  txtInterRegular16: "font-inter font-normal",
  txtMontserratRegular24Gray50: "font-montserrat font-normal",
  txtInterRegular2182: "font-inter font-normal",
  txtLibreFranklinRegular15: "font-librefranklin font-normal",
  txtPoppinsBlack24: "font-black font-poppins",
  txtRobotoRegular18Black900dd: "font-normal font-roboto",
  txtOpenSansRegular24: "font-normal font-opensans",
  txtPoppinsRegular12: "font-normal font-poppins",
  txtLibreFranklinBold60: "font-bold font-librefranklin",
  txtSegoeUI18: "font-normal font-segoeui",
  txtInterLight12: "font-inter font-light",
  txtSegoeUI16: "font-normal font-segoeui",
  txtMontserratRegular18Purple70001: "font-montserrat font-normal",
  txtMontserratSemiBold52Gray800: "font-montserrat font-semibold",
  txtMontserratMedium16Gray80002: "font-medium font-montserrat",
  txtMontserratMedium24WhiteA700: "font-medium font-montserrat",
  txtOpenSansRegular14Blue80033: "font-normal font-opensans",
  txtRobotoRegular14Indigo200: "font-normal font-roboto",
  txtRobotoBlack13: "font-black font-roboto",
  txtMontserratRegular16Gray800: "font-montserrat font-normal",
  txtMontserratMedium16Bluegray90002: "font-medium font-montserrat",
  txtMontserratMedium18Bluegray90001: "font-medium font-montserrat",
  txtRobotoBlack10: "font-black font-roboto",
  txtSegoeUI20: "font-normal font-segoeui",
  txtAsapRegular14AmberA20001: "font-asap font-normal",
  txtRobotoRegular12: "font-normal font-roboto",
  txtRobotoRegular13: "font-normal font-roboto",
  txtFuzzyBubblesRegular24: "font-fuzzybubbles font-normal",
  txtRobotoRegular14: "font-normal font-roboto",
  txtRobotoRegular15: "font-normal font-roboto",
  txtRobotoRegular16: "font-normal font-roboto",
  txtRobotoBlack18: "font-black font-roboto",
  txtRobotoRegular17: "font-normal font-roboto",
  txtRobotoRegular105: "font-normal font-roboto",
  txtRobotoRegular18: "font-normal font-roboto",
  txtMontserratRegular16Gray20002: "font-montserrat font-normal",
  txtInterMedium40: "font-inter font-medium",
  txtRobotoBlack8: "font-black font-roboto",
  txtRobotoBlack9: "font-black font-roboto",
  txtAsapRegular16WhiteA700: "font-asap font-normal",
  txtMontserratRegular16Pink50: "font-montserrat font-normal",
  txtRobotoRegular10: "font-normal font-roboto",
  txtRobotoRegular11: "font-normal font-roboto",
  txtMontserratMedium20: "font-medium font-montserrat",
  txtInterSemiBold1461: "font-inter font-semibold",
  txtMontserratRegular18Gray70003: "font-montserrat font-normal",
  txtRobotoMedium16Gray90002: "font-medium font-roboto",
  txtMontserratMedium24: "font-medium font-montserrat",
  txtPoppinsBold30: "font-bold font-poppins",
  txtInterMedium24: "font-inter font-medium",
  txtMontserratMedium16Purple400: "font-medium font-montserrat",
  txtMontserratRomanRegular14: "font-montserrat font-normal",
  txtRobotoRegular12Black900: "font-normal font-roboto",
  txtInterBold22: "font-bold font-inter",
  txtLibreFranklinMedium34: "font-librefranklin font-medium",
  txtAsapRegular14Orange600: "font-asap font-normal",
  txtRobotoRegular14Gray60001: "font-normal font-roboto",
  txtAsapMedium21: "font-asap font-medium",
  txtRobotoBold20Gray60002: "font-bold font-roboto",
  txtArialNarrowItalic12Green200: "font-arial font-normal",
  txtAsapSemiBold19: "font-asap font-semibold",
  txtRobotoMedium20: "font-medium font-roboto",
  txtRobotoRegular16Gray90002: "font-normal font-roboto",
  txtAsapSemiBold14: "font-asap font-semibold",
  txtFuzzyBubblesRegular24Black90003: "font-fuzzybubbles font-normal",
  txtRobotoRomanMedium22: "font-medium font-roboto",
  txtOpenSansRegular14Black900: "font-normal font-opensans",
  txtInterMedium20WhiteA700: "font-inter font-medium",
  txtInterMedium12: "font-inter font-medium",
  txtMontserratRomanRegular24: "font-montserrat font-normal",
  txtInterMedium14: "font-inter font-medium",
  txtPoppinsBlack24Bluegray800: "font-black font-poppins",
  txtMontserratRomanRegular16: "font-montserrat font-normal",
  txtMochiyPopOneRegular20: "font-mochiypopone font-normal",
  txtLibreFranklinMedium20: "font-librefranklin font-medium",
  txtInterMedium20: "font-inter font-medium",
  txtAsapSemiBold21: "font-asap font-semibold",
  txtOpenSansRegular12Blue80001: "font-normal font-opensans",
  txtRobotoLight32: "font-light font-roboto",
  txtRobotoMedium16: "font-medium font-roboto",
  txtRobotoBold32: "font-bold font-roboto",
  txtArialNarrowItalic14: "font-arial font-normal",
  txtRobotoRegular15Red700: "font-normal font-roboto",
  txtRobotoBold18: "font-bold font-roboto",
  txtRobotoRegular15Gray60002: "font-normal font-roboto",
  txtOpenSansBold26: "font-bold font-opensans",
  txtRobotoBold16Gray60001: "font-bold font-roboto",
  txtRobotoRegular14Bluegray90003: "font-normal font-roboto",
  txtMontserratRegular20: "font-montserrat font-normal",
  txtRobotoRegular14Gray90003: "font-normal font-roboto",
  txtRobotoRegular15Gray80009: "font-normal font-roboto",
  txtPoppinsBold12: "font-bold font-poppins",
  txtMontserratRegular18: "font-montserrat font-normal",
  txtMontserratMedium15WhiteA700: "font-medium font-montserrat",
  txtPoppinsMedium14: "font-medium font-poppins",
  txtMontserratSemiBold52: "font-montserrat font-semibold",
  txtMontserratRegular16: "font-montserrat font-normal",
  txtMontserratRegular14: "font-montserrat font-normal",
  txtMontserratRegular15: "font-montserrat font-normal",
  txtFuzzyBubblesBold16: "font-bold font-fuzzybubbles",
  txtMontserratRegular13: "font-montserrat font-normal",
  txtRobotoBold26: "font-bold font-roboto",
  txtRobotoRegular1488: "font-normal font-roboto",
  txtInterRegular1334: "font-inter font-normal",
  txtRobotoBold20: "font-bold font-roboto",
  txtAsapMedium21PurpleA100: "font-asap font-medium",
  txtOpenSansRegular11Blue80099: "font-normal font-opensans",
  txtMontserratMedium12: "font-medium font-montserrat",
  txtMontserratMedium14: "font-medium font-montserrat",
  txtMontserratMedium13: "font-medium font-montserrat",
  txtMontserratMedium16: "font-medium font-montserrat",
  txtMontserratMedium15: "font-medium font-montserrat",
  txtOpenSansBold18: "font-bold font-opensans",
  txtSpartanRegular15: "font-normal font-spartan",
  txtMontserratMedium18: "font-medium font-montserrat",
  txtInterSemiBold14: "font-inter font-semibold",
  txtMontserratMedium17: "font-medium font-montserrat",
  txtInterSemiBold15: "font-inter font-semibold",
  txtMontserratRegular16Purple400: "font-montserrat font-normal",
  txtOpenSansBold16: "font-bold font-opensans",
  txtOpenSansBold14: "font-bold font-opensans",
  txtInterSemiBold18: "font-inter font-semibold",
  txtMontserratRegular16WhiteA700: "font-montserrat font-normal",
  txtInterSemiBold16: "font-inter font-semibold",
  txtOpenSansBold10: "font-bold font-opensans",
  txtOpenSansRegular14Lightgreen60002: "font-normal font-opensans",
  txtMontserratSemiBold52WhiteA700: "font-montserrat font-semibold",
  txtMontserratRegular24: "font-montserrat font-normal",
  txtRobotoBold15: "font-bold font-roboto",
  txtRobotoBold16: "font-bold font-roboto",
  txtArialBoldMT12Red80001: "font-arial font-bold",
  txtRobotoBold14: "font-bold font-roboto",
  txtAsapBold24: "font-asap font-bold",
  txtRobotoRegular1477: "font-normal font-roboto",
  txtArialNarrowItalic10: "font-arial font-normal",
  txtInterRegular12AmberA40001: "font-inter font-normal",
  txtInterSemiBold1488: "font-inter font-semibold",
  txtRobotoBold12: "font-bold font-roboto",
  txtArialNarrowItalic12: "font-arial font-normal",
  txtInterRegular1048: "font-inter font-normal",
  txtAsapRegular30: "font-asap font-normal",
  txtAsapSemiBold118: "font-asap font-semibold",
  txtRobotoRegular15Gray900: "font-normal font-roboto",
} as const;

export type TextProps = Partial<{
  className: string;
  size: keyof typeof sizeClasses;
  as: any;
}> &
  React.DetailedHTMLProps<
    React.HTMLAttributes<HTMLSpanElement>,
    HTMLSpanElement
  >;

const Text: React.FC<React.PropsWithChildren<TextProps>> = ({
  children,
  className = "",
  size,
  as,
  ...restProps
}) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
